---
# tasks file for ansible-role-zabbix_frontend

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create zabbix_frontend_conf_file
  template:
    src: zabbix.conf.php.j2
    dest: "{{ zabbix_frontend_conf_file }}"
    # validate: echo %s
    mode: '0640'
    owner: "{{ zabbix_frontend_user }}"
    group: "{{ zabbix_frontend_group }}"
